# Generated by Django 5.2.6 on 2025-09-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='icon',
            field=models.CharField(default='01d', max_length=10),
        ),
    ]
