from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class UserWeatherPreference(models.Model):
    """User's weather-related preferences and settings"""
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='weather_preferences')
    default_location = models.CharField(max_length=100, default='Mumbai')
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    
    # Alert preferences
    enable_rain_alerts = models.BooleanField(default=True)
    enable_storm_alerts = models.BooleanField(default=True)
    enable_flood_alerts = models.BooleanField(default=True)
    
    # Notification preferences
    email_notifications = models.BooleanField(default=True)
    sms_notifications = models.BooleanField(default=False)
    push_notifications = models.BooleanField(default=True)
    
    # Custom alert thresholds
    rain_threshold_yellow = models.FloatField(default=2.6)  # mm/hr
    rain_threshold_orange = models.FloatField(default=15.0)
    rain_threshold_red = models.FloatField(default=50.0)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username}'s Weather Preferences"

class WeatherData(models.Model):
    """Weather data from API"""
    city = models.CharField(max_length=100)
    latitude = models.FloatField()
    longitude = models.FloatField()
    temperature = models.FloatField()
    humidity = models.FloatField()
    rainfall = models.FloatField(default=0.0)
    wind_speed = models.FloatField()
    weather_condition = models.CharField(max_length=100)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return f"{self.city} - {self.temperature}°C - {self.timestamp}"

class WeatherAlert(models.Model):
    """Weather alerts generated by the system"""
    ALERT_LEVELS = [
        ('green', 'Normal'),
        ('yellow', 'Be Aware'),
        ('orange', 'Be Prepared'),
        ('red', 'Take Action'),
    ]
    
    ALERT_TYPES = [
        ('rain', 'Heavy Rainfall'),
        ('thunder', 'Thunderstorm'),
        ('wind', 'Strong Winds'),
        ('flood', 'Flood Risk'),
    ]
    
    location = models.CharField(max_length=100)
    alert_level = models.CharField(max_length=10, choices=ALERT_LEVELS)
    alert_type = models.CharField(max_length=20, choices=ALERT_TYPES)
    message = models.TextField()
    rainfall_threshold = models.FloatField()
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField()

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.alert_level.upper()} - {self.location} - {self.alert_type}"

class UserAlertHistory(models.Model):
    """Track which alerts user has seen/acknowledged"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    alert = models.ForeignKey(WeatherAlert, on_delete=models.CASCADE)
    acknowledged = models.BooleanField(default=False)
    acknowledged_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.alert.alert_level} alert"
